name=Senseair Sunrise
version=1.0.0
author=Senseair
maintainer=Senseair
sentence=Library for the Sunrise, Sunlight and S12 Micro sensors families by Senseair
paragraph=Enable to use Sunrise, Sunlight or S12 Micro sensors via I2C/UART
category=Sensors
url=https://github.com/Senseair-AB/Senseair_Sunrise
architectures=*
includes=src/senseair_sunrise.h
depends=
license=BSD-3-Clause