name: Compile Examples

on:
  - push
  - pull_request

jobs:
  compile-examples:
    runs-on: ubuntu-latest
    env:
      SKETCHES_REPORTS_PATH: sketches-reports

    strategy:
      matrix:
        fqbn:
          - arduino:avr:mega
          - arduino:mbed:nano33ble
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Compile examples
        uses: arduino/compile-sketches@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fqbn: ${{ matrix.fqbn }}
          libraries: |
              # Install the library from the local path.
              - source-path: ./
          sketch-paths: |
              - examples
          enable-deltas-report: true
          sketches-report-path: ${{ env.SKETCHES_REPORTS_PATH }}

      - name: Save sketches report as workflow artifact
        uses: actions/upload-artifact@v7
        with:
          if-no-files-found: error
          path: ${{ env.SKETCHES_REPORTS_PATH }}
          name: sketches-report-${{ matrix.fqbn }}
